theme: jekyll-theme-minimal
title: Jake Bloomfeld
description: Computer Science + Business Student 


#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/robhinds
 - title: DZone
   url: https://dzone.com/users/899489/rhinds.html
#Any buzzword skills you want to include
skills:
 - Groovy
 - Spring MVC
 - Spring Boot
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default
#Work experience is required
roles:
 - title: Senior Engineer
   start: 2012
   end: Ongoing
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> I am a senior engineer working closely with the CTO, working across the full-stack, I am involved in all aspects of the technology including the website and back-end services.
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham
